# Configuration for FrugalIoT server
server:
  port: 8080
mqtt:
  broker: ws://naturalinnovation.org:9012
organizations:
  - name: dev
    mqtt_password: public
    projects:
      - name: Lotus Ponds
        track:
          - temperature



