# Configuration for FrugalIoT server
server:
  port: 8080
mqtt:
  broker: ws://naturalinnovation.org:9012
organizations:
  - name: dev
    mqtt_password: public
    projects:
      - name: Lotus Ponds
        nodes:
          - id: esp8266-85ea2b
            track:
            - temperature
            - humidity
          - id: esp8266-95a754
            track:
              - temperature
              - humidity


