// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// name: Frugal-IoT LoRaMesher 
// description: Frugal IoT - LoRaMesher test suite
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
// #define LANGUAGE_DEFAULT "id"' ; Default language for portal (if not en) - de,nl,id currently supported
#define SYSTEM_DISCOVERY_DEBUG
#define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
// #define SYSTEM_MEMORY_DEBUG
#define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_SD_WANT
// #define SYSTEM_TIME_DEBUG
#define SYSTEM_WIFI_DEBUG
// #define SYSTEM_WIFI_SCANPERIOD 50000        ; Slow down scanning so can easier debug LoRaMesher
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_ENSAHT_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
// #define SENSOR_SHT_DEBUG
// #define SENSOR_SHT_ADDRESS 0x45 ; 0x44 (default) or 0x45 for D1 shields
// #define SENSOR_SOIL_DEBUG
// #define DEBUG_DNSSERVER

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_BAND 915.0F ; 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia
    // For lots of debugging uncomment these and the esp_log_level_set in main.cpp
#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers// #define CORE_DEBUG_LEVEL 5 ; To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_loramesher}

// lib_deps = 
//     Frugal-IoT@^0.0.14
    // Libraries specific to this hardware - sensor, actuator, etc
    // robtillaart/SHT85 ; included by frugal-iot (in library.json & library.properties)
    //Comment/Uncomment below two lines to switch between live and "new" version
//     jaimi5/LoRaMesher
    //https://github.com/mitra42/LoRaMesher.git#new_loramesher
// selecting a platform for board descriotions
//platform_esp32 = espressif32 ; this is the default
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp32_exception_decoder
// monitor_filters = esp8266_exception_decoder
// extra_scripts = download_fs.py ; only works if have this file in root of project - from https://github.com/maxgerhardt/pio-esp32-esp8266-filesystem-downloader/blob/main/download_fs.py

// Picks up via LoRaMesher and relays by LoRaMesher - though all that is lower layers

#ifdef ARDUINO_TTGO_LoRa32_v21new
// platform = ${common.platform_esp32}
// board = ttgo-lora32-v21 ; defines ARDUINO_TTGO_LoRa32_v21new
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_PREFIX "lorareceiver"
#define SYSTEM_OTA_SUFFIX "ttgo-lora32-v21"
#define SYSTEM_WIFI_SCANPERIOD 50000 ; Scan infrequently else hard to debug // Scan infrequently else hard to debug// Need min_spiffs.csv as SSD and GFX push it over the size
// board_build.partitions = min_spiffs.csv
// lib_deps = 
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

#endif // ARDUINO_TTGO_LoRa32_v21new

#ifdef ARDUINO_TTGO_LoRa32_v21new
// platform = ${common.platform_esp32}
// board = ttgo-lora32-v21 ; defines ARDUINO_TTGO_LoRa32_v21new
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_PREFIX "lorareceiver"
#define SYSTEM_OTA_SUFFIC "ttgo-lora32-v21"
// Need min_spiffs.csv as SSD and GFX push it over the size
// board_build.partitions = min_spiffs.csv
// lib_deps = 
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13


#endif // ARDUINO_TTGO_LoRa32_v21new

#ifdef ARDUINO_LILYGO_T3_S3_V1_X
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo-t3-s3-sx127x
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_PREFIX "lorasender"
#define SYSTEM_OTA_SUFFIX "lilygo-t3-s3-sx127x"
#define SYSTEM_WIFI_SCANPERIOD 50000 ; Scan infrequently else hard to debug // Scan infrequently else hard to debug#define SYSTEM_LORAMESHER_SENDER
// Need min_spiffs.csv as SSD and GFX push it over the size
// board_build.partitions = min_spiffs.csv
// lib_deps = 
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

#endif // ARDUINO_LILYGO_T3_S3_V1_X

#ifdef TODO_HELTEC_WIFI_LORA_32_V3
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; defines ARDUINO_heltec_wifi_lora_32_V3; default variant heltec_wifi_lora_32_V3
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_PREFIX "lorasender"
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v3"
// #define SYSTEM_WIFI_SCANPERIOD 50000 ; Scan infrequently else hard to debug LoRa
// #define SYSTEM_LORAMESHER_SENDER
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

// This option doesnt actually do LoRa but its to support testing
#endif // TODO_HELTEC_WIFI_LORA_32_V3

#ifdef TODO_ESP32DEV
// platform = espressif32
// board = esp32dev
// framework = arduino
// monitor_speed = 115200
// build_flags =
//     -DCONFIG_ESP_INT_WDT_TIMEOUT_MS=2000
//     -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=10
    #endif // TODO_ESP32DEV

