// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File - Frugal-IoT OSPIT irrigation node
//
// Two boards, deliberately, for the same application:
//
//   ff_openmppt  the FF-ESP32-OpenMPPT solar charge controller OSPIT itself runs on. This is the
//                target board; MPPT is NOT implemented here (that is P4/P5) - the charge control
//                hardware is simply left alone and this build uses the board only for irrigation.
//   s2_mini      a Lolin S2 Mini, i.e. the same application on a plain dev board with no MPPT
//                hardware at all. More pins, less to go wrong, and it proves nothing in the
//                application depends on the charge controller.
//
// They target different ARDUINO_* macros (ARDUINO_ESP32_DEV and ARDUINO_LOLIN_S2_MINI), so
// scripts/generate_platform_h.py emits both into platform.h rather than marking one DISABLED -
// unlike two envs for the same board, where it keeps only the first.

// [platformio]
// name: Frugal-IoT OSPIT
// description: Frugal IoT - OSPIT irrigation - sequenced soil-moisture irrigation with tank and battery interlocks
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps =
//     Frugal-IoT@^0.1.6
    // ModbusMaster (the RS485 soil probes) is a declared dependency of Frugal-IoT, so
    // lib_ldf_mode = chain pulls it in - it does not need listing here.

// lib_deps_oled =
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
// #define CONTROL_IRRIGATION_DEBUG
// #define SENSOR_SOILMODBUS_DEBUG
// #define SYSTEM_MODBUS_DEBUG
// #define SENSOR_ANALOG_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_WIFI_DEBUG
    // Turn off C++ exceptions - nothing in this example throws. See examples/agri/platformio.ini
    // for the measurements behind this.
//     -fno-exceptions

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main =

// project specific flags that are needed by the library
// build_flags_library =
#define SYSTEM_OTA_PREFIX "ospit"

// Ask the linker for a map file - scripts/size_report.py reads it.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// build_flags =
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_map}

// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps = ${common.lib_deps}
// lib_ldf_mode = chain

// ==== FF-ESP32-OpenMPPT =============================================
// The solar charge controller board OSPIT runs on - a plain ESP32. Pin assignments below are
// OSPIT's own, read out of its Lua:
//   valves 26, 27, 12          irrigation.lua `local valves = {26, 27, 12, 14}`
//   pump / load 14             irrigation.lua drives it with the valve when pump_is_load is false;
//                              mp2.lua also uses it as the low-voltage load disconnect, and
//                              control.lua exposes it as "Load power output". Three jobs, one pin.
//   RS485 rx 16 / tx 17        modbr.lua, uart.setup(2, ..., {tx = 17, rx = 16})
//   tank gauge GPIO32          irrigation.lua ADCmeasure(4, 2), i.e. ADC1 channel 4
//   battery GPIO33             mp2.lua Voutmeasure(), ADC1 channel 5, 1k/15k divider = ratio 16
//   OLED I2C 21/22             init.lua loads SSD1306.lua
//
// NOTE the display here is the I2C SSD1306, NOT the SSD1327 SPI panel that examples/all builds for
// this board. The SSD1327 needs dc=16 and rst=17, which are the very UEXT pins the RS485 probes
// use - you get the display or the probes, not both. OSPIT makes the same choice: init.lua loads
// SSD1306.lua and leaves the SSD1327 line commented out.

// ===== [env:ff_openmppt] -> ARDUINO_ESP32_DEV
#ifdef ARDUINO_ESP32_DEV
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = esp32dev ; defines ARDUINO_ESP32_DEV
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ff_openmppt"
    // --- irrigation hardware ---
#define OSPIT_VALVE1_PIN 26
#define OSPIT_VALVE2_PIN 27
#define OSPIT_VALVE3_PIN 12
#define OSPIT_PUMP_PIN 14
#define OSPIT_TANK_PIN 32
    // --- RS485 soil probes, one per sector, slave ids 1..3 ---
#define SENSOR_SOILMODBUS_WANT
#define SYSTEM_RS485_RX_PIN 16
#define SYSTEM_RS485_TX_PIN 17
#define OSPIT_RS485_UART Serial2
    // --- battery, for the low-voltage interlock ---
#define SENSOR_BATTERY_PIN 33
#define SENSOR_BATTERY_VOLTAGE_DIVIDER 16 // 1k/15k, i.e. OSPIT's 0.0625 ratio inverted
    // --- display ---
    // This board has no OLED in its board definition, so the chip, the bus and the panel size all
    // have to be stated explicitly - actuator/oled.h #errors rather than guessing any of them.
#define ACTUATOR_OLED_WANT
#define ACTUATOR_OLED_IS_SSD1306
#define OLED_WIRE Wire
#define OLED_SDA 21
#define OLED_SCL 22
#define OLED_RST_X -1
#define ACTUATOR_OLED_WIDTH 128
#define ACTUATOR_OLED_HEIGHT 64
// lib_deps =
//     ${common.lib_deps_oled}

// ==== Lolin S2 Mini =================================================
// The same application with no charge-controller hardware. Pin choices follow
// https://github.com/mitra42/frugal-iot/wiki/Pin-usage-on-various-dev-boards#lolin-s2-mini :
// every ADC1 pin (GPIO1-10) is left free for analog, and the digital traffic is put on ADC2 pins
// (GPIO11-20), which are unusable for analog anyway once WiFi is up.
#endif // ARDUINO_ESP32_DEV

// ===== [env:s2_mini] -> ARDUINO_LOLIN_S2_MINI
#ifdef ARDUINO_LOLIN_S2_MINI
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"
    // --- irrigation hardware ---
#define OSPIT_VALVE1_PIN 10
#define OSPIT_VALVE2_PIN 13
#define OSPIT_VALVE3_PIN 14
#define OSPIT_PUMP_PIN 38 // digital-only pin; examples/agri already drives 38 as an output
#define OSPIT_TANK_PIN 6 // ADC1_CH5
    // --- RS485 soil probes ---
#define SENSOR_SOILMODBUS_WANT
#define SYSTEM_RS485_RX_PIN 16
#define SYSTEM_RS485_TX_PIN 18
#define OSPIT_RS485_UART Serial1 // The S2 has Serial0 and Serial1 only - there is no Serial2
    // --- battery ---
#define SENSOR_BATTERY_PIN 8 // ADC1_CH7. Note examples/agri uses 16 on this board, which is ADC2
                            // and so subject to the "ADC2 is shared with WiFi" caveat.
#define SENSOR_BATTERY_VOLTAGE_DIVIDER 16 // Assumes you fit the same 1k/15k divider as the FF board
#endif // ARDUINO_LOLIN_S2_MINI

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: ESP32 Dev Module / LOLIN S2 Mini"
#endif

#endif // PLATFORM_H
