// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// name: Frugal-IoT Lilygo HiGrow
// description: Frugal IoT - Lilygo HiGrow plant sensor
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps = 
//     Frugal-IoT@^0.1.5
    // Libraries specific to this hardware - sensor, actuator, etc
    // robtillaart/SHT85 ; included by frugal-iot (in library.json & library.properties)
 
// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
    //Flags usable in specific modules - mostly here for documentation
// #define LANGUAGE_DEFAULT "id" // Default language for portal (if not en) - de,nl,id currently supported
// #define ACTUATOR_LCD_WANT
// #define ACTUATOR_LCD_COLS 20 // uncomment for 20x4 display (default is 16x2)
// #define ACTUATOR_LCD_ROWS 4
// #define SENSOR_BATTERY_PIN 0 // Read battery voltage on pin 0 as its external (note pin 5 failed for some reason)
// #define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 // Typically use a 100k+100k voltage divider on external power supplies
// #define SENSOR_DS18B20_PIN 6
// #define SENSOR_SHT_ADDRESS 0x45 // 0x44 (default) or 0x45 for D1 shields (SHT4x default is also 0x44)
// #define SENSOR_SHT_SHT4x // Uncomment if using SHT4x series sensors (default is SHT3x)
// #define SENSOR_SOIL_PIN 4
    // The ultrasonic sensor talks Modbus over RS485. Its slave id switches on SYSTEM_MODBUS_WANT,
    // which then needs the UART pins as well - all three, or system/modbus.h stops the build with
    // an #error. Costs ~20k of flash (ModbusMaster + the RS485/Modbus classes).
// #define SENSOR_ULTRASONIC_SLAVE_ID 1
// #define SYSTEM_RS485_RX_PIN 20
// #define SYSTEM_RS485_TX_PIN 21
// #define SYSTEM_SD_WANT // Uses LittleFS by default
// #define SYSTEM_WIFI_SCANPERIOD 50000 // Slow down scanning so can easier debug captive portal
    // Flags from other libraries
// #define LORAMESHER_LOG_LEVEL 2 // 0 is LOTS of debugging 2 is less
// #define DEBUG_DNSSERVER // If captive portal not seeing requests - as happening on ESP8266
    // Turn off C++ exceptions. Worth 75,166 bytes on c3_pico (73.3% of the app partition down to
    // ~69.1%): ~53k of that is .eh_frame unwind tables and ~22k is the exception-handling code
    // itself. Nothing in Frugal-IoT catches anything except the LoRaMesher glue in
    // system/loramesher.cpp, so on a non-LoRa board this changes no behaviour.
    // LoRaMesher DOES throw, in ten-odd files, so the LoRa boards take this flag back off again
    // with build_unflags below - see common.build_unflags_loramesher. Removing it that way is
    // free; countering it with -fexceptions instead would cost those boards 6,232 bytes, because
    // -fexceptions also adds unwind tables to C sources that the default leaves out.
    // Note PlatformIO's "Flash: nn%" line does not count .eh_frame, so on the RISC-V boards the
    // real firmware.bin is bigger than reported (c3_pico was 73.3% real vs 70.0% reported). The
    // Xtensa boards fold .eh_frame into .flash.rodata, so their reported figure is about right.
    //-fno-exceptions
    // Uncomment debug lines before as needed
// #define ACTUATOR_LCD_DEBUG
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_CLIMATE_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_AHT_DEBUG
// #define SENSOR_ENS160_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
// #define SENSOR_SHT_DEBUG
// #define SENSOR_SOIL_DEBUG
// #define SYSTEM_DISCOVERY_DEBUG
// #define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
// #define SYSTEM_FS_DEBUG_DIR // List the whole LittleFS directory tree at boot
// #define SYSTEM_MEMORY_DEBUG // cos seeing intermittent crash after some period (>7 mins)
// #define SYSTEM_MESSAGE_DEBUG // report messages received, sent, looped etc
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_WIFI_DEBUG

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 
#define SYSTEM_OTA_PREFIX "lilygohigrow"
#define POWER_CTRL 4 // Required before reading anything TODO-power consumption turnoff outside loops TODO-115 move this to a system_power module
#define LILYGOHIGROW // TODO-141 should be obsoleted by arguments in main.cpp
    // LED automatically included - but doesnt seem to work


// LoRaMesher throws, so the boards that use it need C++ exceptions back on. build_unflags REMOVES
// -fno-exceptions rather than countering it with -fexceptions - measured as byte-identical to a
// build that never had the flag, where -fexceptions would have cost 6,232 bytes.
// build_unflags_loramesher =
//     -fno-exceptions

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia
#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers
// #define CORE_DEBUG_LEVEL 5 // To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC // Debugging from RadioLib 

// Ask the linker for a map file. scripts/size_report.py reads it to say which archive members
// were linked in and which symbol pulled each one - the definitive answer to "is code from a
// sensor I am not using taking up flash". Build-time only, nothing reaches the device.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_map}
   
// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp8266_exception_decoder


// ===== [env:lilygohigrow] -> ARDUINO_ESP32_DEV
#ifdef ARDUINO_ESP32_DEV
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = esp32dev
// monitor_port = /dev/cu.usbserial-58950030781  ; This may be specific to my HiGrow or generic across all ?
// build_flags = 
//     ${common.build_flags}
// board_build.partitions = min_spiffs.csv

// TODO there are several variations of the LilyGo, e.g. using a DHT instead of SHT,
// I do not have these boards to test, so not adding them here
// feel free to add them above
#endif // ARDUINO_ESP32_DEV

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: ESP32 Dev Module"
#endif

#endif // PLATFORM_H
