// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// name: Frugal-IoT Sonoff
// description: Frugal IoT - Sonoff R2 switch
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
// #define LANGUAGE_DEFAULT "id"' ; Default language for portal (if not en) - de,nl,id currently supported
#define SYSTEM_DISCOVERY_DEBUG
#define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
// #define SYSTEM_MEMORY_DEBUG
#define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_SD_WANT
// #define SYSTEM_TIME_DEBUG
#define SYSTEM_WIFI_DEBUG
// #define SYSTEM_WIFI_SCANPERIOD 50000        ; Slow down scanning so can easier debug captive portal
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_ENSAHT_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
// #define SENSOR_SHT_DEBUG
// #define SENSOR_SHT_ADDRESS 0x45 ; 0x44 (default) or 0x45 for D1 shields
// #define SENSOR_SOIL_DEBUG
// #define DEBUG_DNSSERVER

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 
#define SYSTEM_OTA_PREFIX "sonoff"

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_BAND 915.0F ; 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers// #define CORE_DEBUG_LEVEL 5 ; To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}

// lib_deps = 
//     Frugal-IoT@^0.0.16
    // Libraries specific to this hardware - sensor, actuator, etc
    
// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// R4 are definitely 115200 R2 might also be
// monitor_speed = 115200 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 115200
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp32_exception_decoder
// monitor_filters = esp8266_exception_decoder



#ifdef TODO_SONOFF_BASIC
// platform = espressif8266
// board = sonoff_basic
//board = esp01_1m
// ftdi adapter - I think this is my specific one, so probably need to override 
// monitor_port = /dev/cu.usbserial-A5069RR4
// board_build.flash_mode = dout ; unique ? to Sonoff
// build_flags = 
//     ${common.build_flags}
#define SERIAL_BAUD 115200
// #define SYSTEM_OTA_SUFFIX "r2"' ; No OTA_KEY for Sonoff, there is not enough space (code > flash/2)
#define PIN_WIRE_SDA -1 ; To defeat a check in the Wire library that fails compile if there is no PIN_WIRE_SDA and SDA // To defeat a check in the Wire library that fails compile if there is no PIN_WIRE_SDA and SDA#define SDA -1 ; To defeat a check in the Wire library that fails compile if there is no PIN_WIRE_SDA and SDA // To defeat a check in the Wire library that fails compile if there is no PIN_WIRE_SDA and SDA
// Note there are other Sonoffs 
// R3 is reputedly hard to program - inaccessible pins
// R4 is the ESP32 version - have some but not yet tested   


#endif // TODO_SONOFF_BASIC

#ifdef ARDUINO_ESP32C3_DEV
// platform = ${common.platform_esp32}
// board = esp32-c3-devkitm-1
// There is no sonoff_basicr4 variant file - so define locally and will submit PR when tested
// board_build.variants_dir = src/variants
// board_build.variant = sonoff_basicr4
// board_build.partitions = min_spiffs.csv
//board_build.flash_mode = dout ; was required for r2, maybe needed here - also seen dio suggested
// build_flags = 
//     ${common.build_flags}
#define SERIAL_BAUD 115200
#define SYSTEM_BUTTONS_DEBUG
#define SYSTEM_OTA_SUFFIX "r4"
    // I2C and SPI aren't used, but will throw errors, at build, without these pins being set. 
#define PIN_WIRE_SDA -1
#define SDA -1
#define SCL -1
#define MISO -1
#define MOSI -1
#define SCK -1
#define SS -1

// JUST FOR TESTING DO NOT COPY BACK INTO SONOFF/PLATFORM.INI
#endif // ARDUINO_ESP32C3_DEV

#ifdef ARDUINO_LOLIN_S2_MINI
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI variant=lolin_s2_mini
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"
#define SYSTEM_BUTTONS_DEBUG
#define RELAY_BUILTIN 34 ; random place // random place#endif // ARDUINO_LOLIN_S2_MINI

