// Autogenerated by generate_platform_h.py — do not hand-edit.
// Re-run lib/Frugal-IoT/scripts/prerelease.bash after changing platformio.ini.
//
// Arduino IDE users: install the Heltec ESP32 board package via Board Manager
// (URL: https://resource.heltec.cn/download/package_heltec_esp32_index.json)
// before opening gps.ino. Pin constants (SDA_OLED, SCL_OLED, RST_OLED, Vext)
// come from that package's variant file, not from this header.

#define SYSTEM_OTA_PREFIX "gps"
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F
#define SYSTEM_LORAMESHER_DEBUG
// #define SENSOR_GPS_DEBUG

#ifdef ARDUINO_heltec_wifi_lora_32_V4
  #define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v4"
  // GNSS UART pins — from Heltec's own example code (Debug_GNSS.cpp, GPSwithOLED.cpp):
  #define SENSOR_GPS_RX_PIN 39      // ESP32-S3 UART RX ← GNSS module TX
  #define SENSOR_GPS_TX_PIN 38      // ESP32-S3 UART TX → GNSS module RX
  #define SENSOR_GPS_0v_PIN 34      // VGNSS_CTRL — active LOW, power0v_pin
  #define SENSOR_GPS_WAKE_PIN 40    // GNSS_WAKE — drive HIGH to keep module awake
  #define SENSOR_GPS_RST_PIN 42     // GNSS_RST — drive HIGH to release from reset
#endif // ARDUINO_heltec_wifi_lora_32_V4
