// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// Anything matching *-local.ini is loaded on top of this file, and is not committed: that is where
// the enrolment secret goes, and which server this build is for. A GLOB rather than a name, so a
// checkout with no such file builds unchanged instead of erroring.
// extra_configs = *-local.ini

// name: Frugal-IoT All 
// description: Frugal IoT - Combination file - compile and link everything for testing
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps = 
//     Frugal-IoT@^2.0.0
    // Libraries specific to this hardware - sensor, actuator, etc
    // robtillaart/SHT85 ; included by frugal-iot (in library.json & library.properties)
 
// lib_deps_lora = 
//     ${common.lib_deps}
    //Comment/Uncomment below two lines to switch between live and "new" version
    //jaimi5/LoRaMesher
    //Comment/Uncomment below to switch between upstream and our fork.
//         https://github.com/loramesher/LoRaMesher.git
    //https://github.com/mitra42/LoRaMesher.git#perf/avoid-iostreams
    //https://github.com/mitra42/LoRaMesher.git#new_loramesher

// lib_deps_oled =
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

// lib_deps_oled_ssd1327 =
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1327@^1.0.4
//     adafruit/Adafruit GFX Library@^1.10.13

// lib_deps_lora_oled =
//     ${common.lib_deps_lora}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13
    // adafruit/Adafruit BusIO@^1.14.0  ; transitive dep of Adafruit GFX; chain LDF doesn't auto-resolve; unclear if still needed for any boards

// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
    //Flags usable in specific modules - mostly here for documentation
// #define LANGUAGE_DEFAULT "id" // Default language for portal (if not en) - de,nl,id currently supported
// #define ACTUATOR_LCD_WANT
// #define ACTUATOR_LCD_COLS 20 // uncomment for 20x4 display (default is 16x2)
// #define ACTUATOR_LCD_ROWS 4
// #define SENSOR_BATTERY_PIN 0 // Read battery voltage on pin 0 as its external (note pin 5 failed for some reason)
// #define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 // Typically use a 100k+100k voltage divider on external power supplies
// #define SENSOR_DS18B20_PIN 6
// #define SENSOR_SOIL_PIN 4
    // The ultrasonic sensor talks Modbus over RS485. Its slave id switches on SYSTEM_MODBUS_WANT,
    // which then needs the UART pins as well - all three, or system/modbus.h stops the build with
    // an #error. Costs ~20k of flash (ModbusMaster + the RS485/Modbus classes).
// #define SENSOR_ULTRASONIC_SLAVE_ID 1
// #define SYSTEM_RS485_RX_PIN 20
// #define SYSTEM_RS485_TX_PIN 21
// #define SYSTEM_SD_WANT // Uses LittleFS by default
// #define SYSTEM_WIFI_SCANPERIOD 50000 // Slow down scanning so can easier debug captive portal
    // Flags from other libraries
// #define LORAMESHER_LOG_LEVEL 2 // 0 is LOTS of debugging 2 is less
// #define DEBUG_DNSSERVER // If captive portal not seeing requests - as happening on ESP8266
    // Turn off C++ exceptions. Worth 75,166 bytes on c3_pico (73.3% of the app partition down to
    // ~69.1%): ~53k of that is .eh_frame unwind tables and ~22k is the exception-handling code
    // itself. Nothing in Frugal-IoT catches anything except the LoRaMesher glue in
    // system/loramesher.cpp, so on a non-LoRa board this changes no behaviour.
    // LoRaMesher DOES throw, in ten-odd files, so the LoRa boards take this flag back off again
    // with build_unflags below - see common.build_unflags_loramesher. Removing it that way is
    // free; countering it with -fexceptions instead would cost those boards 6,232 bytes, because
    // -fexceptions also adds unwind tables to C sources that the default leaves out.
    // Note PlatformIO's "Flash: nn%" line does not count .eh_frame, so on the RISC-V boards the
    // real firmware.bin is bigger than reported (c3_pico was 73.3% real vs 70.0% reported). The
    // Xtensa boards fold .eh_frame into .flash.rodata, so their reported figure is about right.
    //-fno-exceptions
    // Uncomment debug lines before as needed
// #define ACTUATOR_LCD_DEBUG
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_CLIMATE_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_AHT_DEBUG
// #define SENSOR_ENS160_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
// #define SENSOR_SHT_DEBUG
// #define SENSOR_SOIL_DEBUG
// #define SYSTEM_DISCOVERY_DEBUG
// #define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
#define SYSTEM_LITTLEFS_SUPPORTDEPRECATED // one-shot migration of saved config from /<id>/<leaf>
                                         // directories to flat /<id>.<leaf> files. A LittleFS
                                         // directory costs a 2-block metadata pair (8KB), so the
                                         // old layout filled a 128KB partition after 15 modules.
                                         // Remove once no board in the field has the old layout.
// #define SYSTEM_FS_DEBUG_DIR // List the whole LittleFS directory tree at boot
// #define SYSTEM_MEMORY_DEBUG // cos seeing intermittent crash after some period (>7 mins)
// #define SYSTEM_MESSAGE_DEBUG
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_WIFI_DEBUG

// Filled in by <name>-local.ini - the enrolment secret, and which server to build against.
// Empty here, so this file can be committed and a checkout without a local one still builds.
// build_flags_local =

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 
    // The enrolment secret, and which server this build is for - see <name>-local.ini
//     ${common.build_flags_local}

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 
#define SYSTEM_OTA_PREFIX "all"

// LoRaMesher throws, so the boards that use it need C++ exceptions back on. build_unflags REMOVES
// -fno-exceptions rather than countering it with -fexceptions - measured as byte-identical to a
// build that never had the flag, where -fexceptions would have cost 6,232 bytes.
// build_unflags_loramesher =
//     -fno-exceptions

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia
// #define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers
// #define CORE_DEBUG_LEVEL 5 // To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC // Debugging from RadioLib 

// Ask the linker for a map file. scripts/size_report.py reads it to say which archive members
// were linked in and which symbol pulled each one - the definitive answer to "is code from a
// sensor I am not using taking up flash". Build-time only, nothing reaches the device.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_map}
   
// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp8266_exception_decoder
// monitor_filters = esp32_exception_decoder


// ===== [env:c3_pico] -> ARDUINO_LOLIN_C3_PICO
#if defined(ARDUINO_LOLIN_C3_PICO) || defined(C3_PICO)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_c3_mini ; use c3_mini board defs - but note define below which is special cased
// board_build.variant = lolin_c3_pico
// board_build.partitions = min_spiffs.csv
// build_flags = 
//     ${common.build_flags}
    // A C3 has no DAC, so this env exercises the PWM path - which needs an RC filter on the pin
    // to be a voltage at all, see actuator/analog.h
#define ACTUATOR_ANALOG_PIN 10
#define SYSTEM_OTA_SUFFIX "c3_pico"
#define ARDUINO_LOLIN_C3_PICO // if using C3_PICO use lolin_c3_mini as board and define here
    // PR submitted https://github.com/espressif/arduino-esp32/pull/11851
    // Until then patched into variant file but if that is auto-updated, can define below
    // Remove this comment when PR accepted, and new version of Arudino-esp32 gets installed
    // See Home(bottom left)/Platforms/espresif32/updates (none as of 2025sep23 even though PR merged)
// #define RGB_BUILTIN_LED_COLOR_ORDER LED_COLOR_ORDER_RGB

#endif // ARDUINO_LOLIN_C3_PICO

// ===== [env:s2_mini] -> ARDUINO_LOLIN_S2_MINI
#if defined(ARDUINO_LOLIN_S2_MINI) || defined(S2_MINI)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"

#endif // ARDUINO_LOLIN_S2_MINI

// ===== [env:nodemcu-32s] -> ARDUINO_NodeMCU_32S
#if defined(ARDUINO_NodeMCU_32S) || defined(NODEMCU_32S)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = nodemcu-32s
// build_flags = 
//     ${common.build_flags}
    // Compile coverage for the RS485/Modbus path. The soil probes need no slave id here - theirs
    // are constructor arguments, one per sector - but they do need the bus pins, and defining
    // SENSOR_SOILMODBUS_WANT turns on SYSTEM_MODBUS_WANT which #errors without them.
#define SENSOR_SOILMODBUS_WANT
#define SYSTEM_RS485_RX_PIN 16
#define SYSTEM_RS485_TX_PIN 17
    // GPIO 25 is DAC1 on a plain ESP32, so this env exercises the DAC path
#define ACTUATOR_ANALOG_PIN 25
#define SYSTEM_OTA_SUFFIX "nodemcu-32s"
// board_build.partitions = min_spiffs.csv

// ==== FF-ESP32-OpenMPPT ============================================
// The solar charge controller board OSPIT runs on - a plain ESP32 with an I2C OLED on 21/22 and
// a UEXT header carrying UART2 and HSPI. Two envs because the header cannot do both jobs at once:
// see the note on the ssd1327 env below.

#endif // ARDUINO_NodeMCU_32S

// ===== [env:ff_openmppt_ssd1327] -> ARDUINO_ESP32_DEV
#if defined(ARDUINO_ESP32_DEV) || defined(FF_OPENMPPT_SSD1327)
#define FRUGAL_IOT_BOARD_CONFIGURED
// Only one FF env, deliberately. Arduino has no concept of environments - it compiles one config
// per board - so generate_platform_h.py keeps the first env targeting a given ARDUINO_* macro and
// marks any later one DISABLED. Two FF envs therefore look fine and silently build the same
// firmware twice. This example exists for compile coverage, so the env here is the one that
// exercises the SSD1327 path; a node that wants the I2C SSD1306 this board more usually carries
// sets instead:
// #define ACTUATOR_OLED_IS_SSD1306
// #define OLED_RST_X -1 -D ACTUATOR_OLED_WIDTH=128 -D ACTUATOR_OLED_HEIGHT=64
// with lib_deps ${common.lib_deps_oled}.
// MUTUALLY EXCLUSIVE WITH THE MODBUS SOIL SENSORS. The panel needs dc=16 and rst=17, which are
// the UEXT RX_2/TX_2 pins - and those are exactly the pins OSPIT drives UART2 on for its
// RS485 soil probes (uart.setup(2, ..., {tx = 17, rx = 16})). You get the display or the probes,
// not both, which is why OSPIT's own init.lua loads SSD1306.lua and leaves the SSD1327 line
// commented out: on an irrigation controller the probes win.
// platform = ${common.platform_esp32}
// board = esp32dev
// build_flags =
//     ${common.build_flags}
#define ACTUATOR_OLED_WANT
#define ACTUATOR_OLED_IS_SSD1327
#define ACTUATOR_OLED_SPI_SCLK 18
#define ACTUATOR_OLED_SPI_MOSI 23
#define ACTUATOR_OLED_SPI_CS 5
#define ACTUATOR_OLED_SPI_DC 16
#define ACTUATOR_OLED_SPI_RST 17
#define SYSTEM_OTA_SUFFIX "ff_openmppt_ssd1327"
// board_build.partitions = min_spiffs.csv
// lib_deps =
//     ${common.lib_deps_oled_ssd1327}

// ==== ESP8266 boards ================================================

#endif // ARDUINO_ESP32_DEV

// ===== [env:ttgo-lora32-v21] -> ARDUINO_TTGO_LoRa32_v21new
#if defined(ARDUINO_TTGO_LoRa32_v21new) || defined(TTGO_LORA32_V21)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = ttgo-lora32-v21 ; defines ARDUINO_TTGO_LoRa32_v21new
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ttgo-lora32-v21"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_TTGO_LoRa32_v21new

// LILYGO_T3_S3_SX127X, LILYGO_T3_S3_SX127X_SHT are alternative [env:] settings for one board - at most one.
#if (defined(LILYGO_T3_S3_SX127X) + defined(LILYGO_T3_S3_SX127X_SHT)) > 1
  #error "Define at most one of LILYGO_T3_S3_SX127X, LILYGO_T3_S3_SX127X_SHT - they are alternative settings for the same board, and defining two applies both."
#endif
// ===== [env:lilygo_t3_s3_sx127x] -> ARDUINO_LILYGO_T3_S3_V1_X, the DEFAULT for this board
#if (defined(ARDUINO_LILYGO_T3_S3_V1_X) && !defined(LILYGO_T3_S3_SX127X_SHT)) || defined(LILYGO_T3_S3_SX127X)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo_t3_s3_sx127x
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "lilygo_t3_s3_sx127x"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_LILYGO_T3_S3_V1_X

// ----- [env:lilygo_t3_s3_sx127x_sht] also targets ARDUINO_LILYGO_T3_S3_V1_X
// Only one env per board can be active in the Arduino IDE, and [env:lilygo_t3_s3_sx127x]
// is the default. To use this one instead, define LILYGO_T3_S3_SX127X_SHT for the WHOLE
// build - it has to reach the library's sources too, so a #define in the .ino
// is not enough. Either:
//   put the flag -DLILYGO_T3_S3_SX127X_SHT (not a #define) in a file called build_opt.h
//     beside the .ino - it survives this file being regenerated - or
//   #define LILYGO_T3_S3_SX127X_SHT at the TOP of this file, which regenerating discards.
// To make it the default instead, and so need no define at all, set
//   custom_arduino_default = yes
// on [env:lilygo_t3_s3_sx127x_sht] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if defined(LILYGO_T3_S3_SX127X_SHT)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo_t3_s3_sx127x
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "lilygo_t3_s3_sx127x_sht"
#define SENSOR_SHT_WANT // I2C Sensor
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // LILYGO_T3_S3_SX127X_SHT

// HELTEC_WIFI_LORA_32_V3, HELTEC_WIFI_LORA_32_V32 are alternative [env:] settings for one board - at most one.
#if (defined(HELTEC_WIFI_LORA_32_V3) + defined(HELTEC_WIFI_LORA_32_V32)) > 1
  #error "Define at most one of HELTEC_WIFI_LORA_32_V3, HELTEC_WIFI_LORA_32_V32 - they are alternative settings for the same board, and defining two applies both."
#endif
// ===== [env:heltec_wifi_lora_32_V3] -> ARDUINO_heltec_wifi_lora_32_V3, the DEFAULT for this board
#if (defined(ARDUINO_heltec_wifi_lora_32_V3) && !defined(HELTEC_WIFI_LORA_32_V32)) || defined(HELTEC_WIFI_LORA_32_V3)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; there are not yet separate board and variant files for V3
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v3"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_heltec_wifi_lora_32_V3

// ----- [env:heltec_wifi_lora_32_V32] also targets ARDUINO_heltec_wifi_lora_32_V3
// Only one env per board can be active in the Arduino IDE, and [env:heltec_wifi_lora_32_V3]
// is the default. To use this one instead, define HELTEC_WIFI_LORA_32_V32 for the WHOLE
// build - it has to reach the library's sources too, so a #define in the .ino
// is not enough. Either:
//   put the flag -DHELTEC_WIFI_LORA_32_V32 (not a #define) in a file called build_opt.h
//     beside the .ino - it survives this file being regenerated - or
//   #define HELTEC_WIFI_LORA_32_V32 at the TOP of this file, which regenerating discards.
// To make it the default instead, and so need no define at all, set
//   custom_arduino_default = yes
// on [env:heltec_wifi_lora_32_V32] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if defined(HELTEC_WIFI_LORA_32_V32)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; defines ARDUINO_heltec_wifi_lora_32_V3; default variant heltec_wifi_lora_32_V3
// build_flags = 
//     ${common.build_flags}
#define ARDUINO_heltec_wifi_lora_32_V32 // If using 3.2 board uncomment this
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v32"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // HELTEC_WIFI_LORA_32_V32

// TBEAM, TBEAM_OLED are alternative [env:] settings for one board - at most one.
#if (defined(TBEAM) + defined(TBEAM_OLED)) > 1
  #error "Define at most one of TBEAM, TBEAM_OLED - they are alternative settings for the same board, and defining two applies both."
#endif
// ===== [env:tbeam] -> ARDUINO_T_Beam, the DEFAULT for this board
#if (defined(ARDUINO_T_Beam) && !defined(TBEAM_OLED)) || defined(TBEAM)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = ttgo-t-beam ; defines ARDUINO_T_Beam
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "tbeam"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora}

#endif // ARDUINO_T_Beam

// ----- [env:tbeam_oled] also targets ARDUINO_T_Beam
// Only one env per board can be active in the Arduino IDE, and [env:tbeam]
// is the default. To use this one instead, define TBEAM_OLED for the WHOLE
// build - it has to reach the library's sources too, so a #define in the .ino
// is not enough. Either:
//   put the flag -DTBEAM_OLED (not a #define) in a file called build_opt.h
//     beside the .ino - it survives this file being regenerated - or
//   #define TBEAM_OLED at the TOP of this file, which regenerating discards.
// To make it the default instead, and so need no define at all, set
//   custom_arduino_default = yes
// on [env:tbeam_oled] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if defined(TBEAM_OLED)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = ttgo-t-beam ; defines ARDUINO_T_Beam
// build_flags =
//     ${common.build_flags}
    // OLED is an add on for tbeams
#define OLED_SDA 21
#define OLED_SCL 22
#define SYSTEM_OTA_SUFFIX "tbeam_oled"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora_oled}

#endif // TBEAM_OLED

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: LOLIN C3 Pico / LOLIN S2 Mini / NodeMCU-32S / ESP32 Dev Module / TTGO LoRa32-OLED, with Board Revision = TTGO LoRa32 V2.1 (1.6.1) / LilyGo T3-S3 / Heltec WiFi LoRa 32(V3) / T-Beam"
#endif

#endif // PLATFORM_H
