// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
//
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// name: Frugal-IoT Rain
// description: Frugal IoT - Rain Gauge from an LM393-based analog rain board
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps =
//     Frugal-IoT@^0.1.1
    // Libraries specific to this hardware - sensor, actuator, etc

// lib_deps_lora =
//     ${common.lib_deps}
    //Comment/Uncomment below two lines to switch between live and "new" version
    //jaimi5/LoRaMesher
//     https://github.com/loramesher/LoRaMesher.git
    //https://github.com/mitra42/LoRaMesher.git#new_loramesher

// lib_deps_lora_oled =
//     ${common.lib_deps_lora}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13
    // adafruit/Adafruit BusIO@^1.14.0  ; transitive dep of Adafruit GFX; chain LDF doesn't auto-resolve; unclear if still needed for any boards


// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
    //Flags usable in specific modules - mostly here for documentation
// #define LANGUAGE_DEFAULT "id"'         ; Default language for portal (if not en) - de,nl,id currently supported
// #define ACTUATOR_LCD_WANT
// #define ACTUATOR_LCD_COLS 20            ; uncomment for 20x4 display (default is 16x2)
// #define ACTUATOR_LCD_ROWS 4
// #define SENSOR_BATTERY_PIN 0            ; Read battery voltage on pin 0 as its external (note pin 5 failed for some reason)
// #define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 ; Typically use a 100k+100k voltage divider on external power supplies
// #define SENSOR_RAIN_SCALE 0.01          ; Overrides the "just at first start" default - real value comes from calibrate()
// #define SYSTEM_SD_WANT
// #define SYSTEM_WIFI_SCANPERIOD 50000    ; Slow down scanning so can easier debug captive portal
    // Flags from other libraries
// #define LORAMESHER_LOG_LEVEL 2          ; 0 is LOTS of debugging 2 is less
// #define DEBUG_DNSSERVER
    // Uncomment debug lines below as needed
// #define ACTUATOR_LEDBUILTIN_DEBUG
// #define ACTUATOR_LCD_DEBUG
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_RAIN_DEBUG
// #define SYSTEM_DISCOVERY_DEBUG
// #define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
// #define SYSTEM_MEMORY_DEBUG
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_WIFI_DEBUG

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main =

// project specific flags that are needed by the library
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library =
#define SYSTEM_OTA_PREFIX "rain"

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher =
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F ; 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers// #define CORE_DEBUG_LEVEL 5 ; To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC

// Flags specific to project, but vary across dev-boards or variants
// build_flags =
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}

// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp8266_exception_decoder
// monitor_filters = esp32_exception_decoder


#ifdef ARDUINO_LOLIN_C3_PICO
// platform = ${common.platform_esp32}
// board = lolin_c3_mini ; use c3_mini board defs - but note define below which is special cased
// board_build.variant = lolin_c3_pico
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "c3_pico"
#define ARDUINO_LOLIN_C3_PICO // if using C3_PICO use lolin_c3_mini as board and define here    // Confirmed working analog pin on this board - see sensor/analog.cpp notes
#define SENSOR_RAIN_PIN 4

#endif // ARDUINO_LOLIN_C3_PICO

#ifdef ARDUINO_LOLIN_S2_MINI
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"
// #define SENSOR_RAIN_PIN <n> for this board - not yet verified which analog pins work

#endif // ARDUINO_LOLIN_S2_MINI

#ifdef ARDUINO_NodeMCU_32S
// platform = ${common.platform_esp32}
// board = nodemcu-32s
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "nodemcu-32s"
// #define SENSOR_RAIN_PIN <n> for this board - not yet verified which analog pins work
// board_build.partitions = min_spiffs.csv

// ==== ESP8266 boards ================================================

#endif // ARDUINO_NodeMCU_32S

#ifdef ARDUINO_ESP8266_WEMOS_D1MINIPRO
// platform = espressif8266
// board = d1_mini_pro
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "d1_mini_pro"
// #define SENSOR_RAIN_PIN A0
// board_build.partitions = min_spiffs.csv

#endif // ARDUINO_ESP8266_WEMOS_D1MINIPRO

#ifdef ARDUINO_ESP8266_WEMOS_D1MINI
// board = d1_mini
// platform = espressif8266
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "d1_mini"
// #define SENSOR_RAIN_PIN A0

// ===== LORA BOARDS - ALL ESP32 ======================================

#endif // ARDUINO_ESP8266_WEMOS_D1MINI

#ifdef ARDUINO_TTGO_LoRa32_v21new
// platform = ${common.platform_esp32}
// board = ttgo-lora32-v21 ; defines ARDUINO_TTGO_LoRa32_v21new
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ttgo-lora32-v21"
//     ${common.build_flags_loramesher}
// #define SENSOR_RAIN_PIN <n> for this board - not yet verified which analog pins work
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_TTGO_LoRa32_v21new

#ifdef ARDUINO_LILYGO_T3_S3_V1_X
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo_t3_s3_sx127x
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "lilygo_t3_s3_sx127x"
//     ${common.build_flags_loramesher}
// #define SENSOR_RAIN_PIN <n> for this board - not yet verified which analog pins work
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora_oled}
#endif // ARDUINO_LILYGO_T3_S3_V1_X

