// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// name: Frugal-IoT SHT30
// description: Frugal IoT - Temperature and Humidity Sensor with SHT3x or SHT4x
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps = 
//     Frugal-IoT@^0.1.5
    // Libraries specific to this hardware - sensor, actuator, etc
    // robtillaart/SHT85 ; included by frugal-iot (in library.json & library.properties)

// lib_deps_lora = 
//     ${common.lib_deps}
    //Comment/Uncomment below two lines to switch between live and "new" version
    //jaimi5/LoRaMesher
    //Comment/Uncomment below to switch between upstream and our fork.
    //Upstream, once mitra42/LoRaMesher#perf/avoid-iostreams (or equivalent) is merged there:
    //https://github.com/loramesher/LoRaMesher.git
    //Our fork, branched from upstream 1abec4a. Drops C++ iostreams from LoRaMesher's diagnostic
    //string building, which was anchoring the whole std::locale facet set: worth 230,464 bytes
    //(t3_s3 94.5% -> 82.8%). See FLASH_SIZE.md.
//     https://github.com/mitra42/LoRaMesher.git#perf/avoid-iostreams
    //https://github.com/mitra42/LoRaMesher.git#new_loramesher

// lib_deps_lora_oled =
//     ${common.lib_deps_lora}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13
    // adafruit/Adafruit BusIO@^1.14.0  ; transitive dep of Adafruit GFX; chain LDF doesn't auto-resolve; unclear if still needed for any boards

 
// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
    //Flags usable in specific modules - mostly here for documentation
// #define LANGUAGE_DEFAULT "id" // Default language for portal (if not en) - de,nl,id currently supported
// #define ACTUATOR_LCD_WANT
// #define ACTUATOR_LCD_COLS 20 // uncomment for 20x4 display (default is 16x2)
// #define ACTUATOR_LCD_ROWS 4
// #define SENSOR_BATTERY_PIN 0 // Read battery voltage on pin 0 as its external (note pin 5 failed for some reason)
// #define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 // Typically use a 100k+100k voltage divider on external power supplies
// #define SENSOR_DS18B20_PIN 6
// #define SENSOR_SHT_ADDRESS 0x45 // 0x44 (default) or 0x45 for D1 shields (SHT4x default is also 0x44)
// #define SENSOR_SHT_SHT4x // Uncomment if using SHT4x series sensors (default is SHT3x)
// #define SENSOR_SOIL_PIN 4
    // The ultrasonic sensor talks Modbus over RS485. Its slave id switches on SYSTEM_MODBUS_WANT,
    // which then needs the UART pins as well - all three, or system/modbus.h stops the build with
    // an #error. Costs ~20k of flash (ModbusMaster + the RS485/Modbus classes).
// #define SENSOR_ULTRASONIC_SLAVE_ID 1
// #define SYSTEM_RS485_RX_PIN 20
// #define SYSTEM_RS485_TX_PIN 21
// #define SYSTEM_SD_WANT // Uses LittleFS by default
// #define SYSTEM_WIFI_SCANPERIOD 50000 // Slow down scanning so can easier debug captive portal
    // Flags from other libraries
// #define LORAMESHER_LOG_LEVEL 2 // 0 is LOTS of debugging 2 is less
// #define DEBUG_DNSSERVER // If captive portal not seeing requests - as happening on ESP8266
    // Turn off C++ exceptions. Worth 75,166 bytes on c3_pico (73.3% of the app partition down to
    // ~69.1%): ~53k of that is .eh_frame unwind tables and ~22k is the exception-handling code
    // itself. Nothing in Frugal-IoT catches anything except the LoRaMesher glue in
    // system/loramesher.cpp, so on a non-LoRa board this changes no behaviour.
    // LoRaMesher DOES throw, in ten-odd files, so the LoRa boards take this flag back off again
    // with build_unflags below - see common.build_unflags_loramesher. Removing it that way is
    // free; countering it with -fexceptions instead would cost those boards 6,232 bytes, because
    // -fexceptions also adds unwind tables to C sources that the default leaves out.
    // Note PlatformIO's "Flash: nn%" line does not count .eh_frame, so on the RISC-V boards the
    // real firmware.bin is bigger than reported (c3_pico was 73.3% real vs 70.0% reported). The
    // Xtensa boards fold .eh_frame into .flash.rodata, so their reported figure is about right.
    //-fno-exceptions
    // Uncomment debug lines before as needed
// #define ACTUATOR_LEDBUILTIN_DEBUG
// #define ACTUATOR_LCD_DEBUG
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_CLIMATE_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_AHT_DEBUG
// #define SENSOR_ENS160_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
#define SENSOR_SHT_DEBUG
// #define SENSOR_SOIL_DEBUG
// #define SYSTEM_DISCOVERY_DEBUG
// #define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
// #define SYSTEM_FS_DEBUG_DIR // List the whole LittleFS directory tree at boot
// #define SYSTEM_MEMORY_DEBUG // cos seeing intermittent crash after some period (>7 mins)
#define SYSTEM_MESSAGE_DEBUG
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_WIFI_DEBUG

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 
    // Specific to SHT 
// #define SENSOR_SHT_ADDRESS 0x45 // 0x44 (default) or 0x45 for D1 shields (SHT4x default is also 0x44)
#define SYSTEM_OTA_PREFIX "sht30"

// LoRaMesher throws, so the boards that use it need C++ exceptions back on. build_unflags REMOVES
// -fno-exceptions rather than countering it with -fexceptions - measured as byte-identical to a
// build that never had the flag, where -fexceptions would have cost 6,232 bytes.
// build_unflags_loramesher =
//     -fno-exceptions

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia
#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers
// #define CORE_DEBUG_LEVEL 5 // To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC // Debugging from RadioLib 

// Ask the linker for a map file. scripts/size_report.py reads it to say which archive members
// were linked in and which symbol pulled each one - the definitive answer to "is code from a
// sensor I am not using taking up flash". Build-time only, nothing reaches the device.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_map}
   
// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp8266_exception_decoder
// monitor_filters = esp32_exception_decoder


// ===== [env:c3_pico] -> ARDUINO_LOLIN_C3_PICO
#ifdef ARDUINO_LOLIN_C3_PICO
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_c3_mini ; use c3_mini board defs - but note define below which is special cased
// board_build.variant = lolin_c3_pico
// board_build.partitions = min_spiffs.csv
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "c3_pico"
#define ARDUINO_LOLIN_C3_PICO // if using C3_PICO use lolin_c3_mini as board and define here
    // PR submitted https://github.com/espressif/arduino-esp32/pull/11851
    // Until then patched into variant file but if that is auto-updated, can define below
    // Remove this comment when PR accepted, and new version of Arudino-esp32 gets installed
    // See Home(bottom left)/Platforms/espresif32/updates (none as of 2025sep23 even though PR merged)
// #define RGB_BUILTIN_LED_COLOR_ORDER LED_COLOR_ORDER_RGB

#endif // ARDUINO_LOLIN_C3_PICO

// ===== [env:s2_mini] -> ARDUINO_LOLIN_S2_MINI
#ifdef ARDUINO_LOLIN_S2_MINI
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"

#endif // ARDUINO_LOLIN_S2_MINI

// ----- [env:s2_mini_4x] also targets ARDUINO_LOLIN_S2_MINI, DISABLED
// Only one env per board can be active in the Arduino IDE, and
// [env:s2_mini] is the one in effect. To use this one instead, set
//   custom_arduino_default = yes
// on [env:s2_mini_4x] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if 0
#ifdef ARDUINO_LOLIN_S2_MINI
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini_4x"
#define SENSOR_SHT_SHT4x // Uncomment if using SHT4x series sensors (default is SHT3x)

#endif // ARDUINO_LOLIN_S2_MINI
#endif // 0

// ===== [env:nodemcu-32s] -> ARDUINO_NodeMCU_32S
#ifdef ARDUINO_NodeMCU_32S
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = nodemcu-32s
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "nodemcu-32s"
// board_build.partitions = min_spiffs.csv

// An affordable C3 with a small HW675 OLED 
#endif // ARDUINO_NodeMCU_32S

// ===== [env:esp32c3_oled_72x40] -> ARDUINO_LOLIN_C3_MINI
#ifdef ARDUINO_LOLIN_C3_MINI
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_c3_mini ; use c3_mini board defs - but note define below which is special cased
// board_build.variant = lolin_c3_pico
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "c3_oled_72x40"
#define ARDUINO_C3_OLED_72x40 // if using the C3/small OLED board define here
#define ACTUATOR_OLED_WANT
#define ACTUATOR_OLED_DEBUG // Still debugging this one
// lib_deps = 
//     ${common.lib_deps}  
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13
// board_build.partitions = min_spiffs.csv

// This is the tiny supermini board from Tencent (and clones)
#endif // ARDUINO_LOLIN_C3_MINI

// ===== [env:supermini-4x] -> ARDUINO_NOLOGO_ESP32C3_SUPER_MINI
#ifdef ARDUINO_NOLOGO_ESP32C3_SUPER_MINI
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = nologo_esp32c3_super_mini // defines -DARDUINO_ESP32C3_DEV (as does esp32-c3-devkitm-1)
// monochrome LED on GPIO8, unlike esp32-c3-devkitm-1's RGB LED
// variant defaults to nologo_esp32c3_super_mini
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "supermini-4x"
    // SDA=8 SCL=9(grey) is the standard for this board but 8 is LED, so override with I2C_SDA and I2C_SCL
#define I2C_SDA 6
#define I2C_SCL 5
#define SENSOR_SHT_POWER3v3_PIN 7
#define SENSOR_SHT_SHT4x // Uncomment if using SHT4x series sensors (default is SHT3x)
#define SYSTEM_MDNS_WANT // device should report directly to other local devices
#define SYSTEM_MDNS_DEBUG
 
// ==== ESP8266 boards ================================================

#endif // ARDUINO_NOLOGO_ESP32C3_SUPER_MINI

// ===== [env:ttgo-lora32-v21] -> ARDUINO_TTGO_LoRa32_v21new
#ifdef ARDUINO_TTGO_LoRa32_v21new
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = ttgo-lora32-v21 ; defines ARDUINO_TTGO_LoRa32_v21new
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ttgo-lora32-v21"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_TTGO_LoRa32_v21new

// ===== [env:lilygo_t3_s3_sx127x] -> ARDUINO_LILYGO_T3_S3_V1_X
#ifdef ARDUINO_LILYGO_T3_S3_V1_X
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo_t3_s3_sx127x
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "lilygo_t3_s3_sx127x"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_LILYGO_T3_S3_V1_X

// ----- [env:lilygo_t3_s3_sx127x_sht] also targets ARDUINO_LILYGO_T3_S3_V1_X, DISABLED
// Only one env per board can be active in the Arduino IDE, and
// [env:lilygo_t3_s3_sx127x] is the one in effect. To use this one instead, set
//   custom_arduino_default = yes
// on [env:lilygo_t3_s3_sx127x_sht] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if 0
#ifdef ARDUINO_LILYGO_T3_S3_V1_X
// platform = ${common.platform_esp32}
// board = lilygo-t3-s3 ; defines ARDUINO_LILYGO_T3_S3_V1_X
// board_build.variant = lilygo_t3_s3_sx127x
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "lilygo_t3_s3_sx127x_sht"
#define SENSOR_SHT_WANT // I2C Sensor
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_LILYGO_T3_S3_V1_X
#endif // 0

// ===== [env:heltec_wifi_lora_32_V3] -> ARDUINO_heltec_wifi_lora_32_V3
#ifdef ARDUINO_heltec_wifi_lora_32_V3
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; there are not yet separate board and variant files for V3
// build_flags = 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v3"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_heltec_wifi_lora_32_V3

// ----- [env:heltec_wifi_lora_32_V32] also targets ARDUINO_heltec_wifi_lora_32_V3, DISABLED
// Only one env per board can be active in the Arduino IDE, and
// [env:heltec_wifi_lora_32_V3] is the one in effect. To use this one instead, set
//   custom_arduino_default = yes
// on [env:heltec_wifi_lora_32_V32] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if 0
#ifdef ARDUINO_heltec_wifi_lora_32_V3
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; defines ARDUINO_heltec_wifi_lora_32_V3; default variant heltec_wifi_lora_32_V3
// build_flags = 
//     ${common.build_flags}
#define ARDUINO_heltec_wifi_lora_32_V32 // If using 3.2 board uncomment this
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v32"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_heltec_wifi_lora_32_V3
#endif // 0

// ===== [env:tbeam] -> ARDUINO_T_Beam
#ifdef ARDUINO_T_Beam
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = ttgo-t-beam ; defines ARDUINO_T_Beam
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ttgo-t-beam"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora}

#endif // ARDUINO_T_Beam

// ----- [env:tbeam_oled] also targets ARDUINO_T_Beam, DISABLED
// Only one env per board can be active in the Arduino IDE, and
// [env:tbeam] is the one in effect. To use this one instead, set
//   custom_arduino_default = yes
// on [env:tbeam_oled] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if 0
#ifdef ARDUINO_T_Beam
// platform = ${common.platform_esp32}
// board = ttgo-t-beam ; defines ARDUINO_T_Beam
// build_flags =
//     ${common.build_flags}
    // OLED is an add on for tbeams
#define OLED_SDA 21
#define OLED_SCL 22
#define SYSTEM_OTA_SUFFIX "ttgo-t-beam-oled"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; Need min_spiffs.csv as SSD and GFX push it over the size
// lib_deps =
//     ${common.lib_deps_lora_oled}

#endif // ARDUINO_T_Beam
#endif // 0

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: LOLIN C3 Pico / LOLIN S2 Mini / NodeMCU-32S / LOLIN C3 Mini / Nologo ESP32C3 Super Mini / TTGO LoRa32-OLED, with Board Revision = TTGO LoRa32 V2.1 (1.6.1) / LilyGo T3-S3 / Heltec WiFi LoRa 32(V3) / T-Beam"
#endif

#endif // PLATFORM_H
