// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File
//
//   Build options: build flags, source filter
//   Upload options: custom upload port, speed and extra flags
//   Library options: dependencies, extra library storages
//   Advanced options: extra scripting
//
// Please visit documentation for the other options and examples
// https://docs.platformio.org/page/projectconf.html
// 
// Note the board name is defined in e.g. ~/.platformio/platforms/espressif32/boards/ttgo-lora32-v21.json
// and variants are in ~/.platformio/packages/framework-arduinoespressif32/variants/
// or ~/.platformio/packages/framework-arduinoespressif8266/variants


// custom common options

// [platformio]
// Anything matching *-local.ini is loaded on top of this file, and is not committed: that is where
// the enrolment secret goes, and which server this build is for. A GLOB rather than a name, so a
// checkout with no such file builds unchanged instead of erroring.
// extra_configs = *-local.ini

// name: Frugal-IoT Common Ground
// description: Frugal IoT - Common Ground device
// src_dir = .
//This src_dir line should be present if your program is in xxx.ino or commented out if your program is in src/main.cpp

// [common]
// lib_deps = 
//     Frugal-IoT@^2.0.0
    // Libraries specific to this hardware - sensor, actuator, etc
    // robtillaart/SHT85 ; included by frugal-iot (in library.json & library.properties)
 
// lib_deps_lora = 
//     ${common.lib_deps}
    //Comment/Uncomment below two lines to switch between live and "new" version
    //jaimi5/LoRaMesher
    //Comment/Uncomment below to switch between upstream and our fork.
//         https://github.com/loramesher/LoRaMesher.git
    //https://github.com/mitra42/LoRaMesher.git#perf/avoid-iostreams
    //https://github.com/mitra42/LoRaMesher.git#new_loramesher

// lib_deps_lora_oled =
//     ${common.lib_deps_lora}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13
    // adafruit/Adafruit BusIO@^1.14.0  ; transitive dep of Adafruit GFX; chain LDF doesn't auto-resolve; unclear if still needed for any boards

// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
    //Flags usable in specific modules - mostly here for documentation
// #define LANGUAGE_DEFAULT "id" // Default language for portal (if not en) - de,nl,id currently supported
// #define ACTUATOR_LCD_WANT
// #define ACTUATOR_LCD_COLS 20 // uncomment for 20x4 display (default is 16x2)
// #define ACTUATOR_LCD_ROWS 4
// #define SENSOR_BATTERY_PIN 0 // Read battery voltage on pin 0 as its external (note pin 5 failed for some reason)
// #define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 // Typically use a 100k+100k voltage divider on external power supplies
// #define SENSOR_DS18B20_PIN 6
// #define SENSOR_SOIL_PIN 4
    // The ultrasonic sensor talks Modbus over RS485. Its slave id switches on SYSTEM_MODBUS_WANT,
    // which then needs the UART pins as well - all three, or system/modbus.h stops the build with
    // an #error. Costs ~20k of flash (ModbusMaster + the RS485/Modbus classes).
// #define SENSOR_ULTRASONIC_SLAVE_ID 1
// #define SYSTEM_RS485_RX_PIN 20
// #define SYSTEM_RS485_TX_PIN 21
// #define SYSTEM_SD_WANT // Uses LittleFS by default
// #define SYSTEM_WIFI_SCANPERIOD 50000 // Slow down scanning so can easier debug captive portal
    // Flags from other libraries
// #define LORAMESHER_LOG_LEVEL 2 // 0 is LOTS of debugging 2 is less
// #define DEBUG_DNSSERVER // If captive portal not seeing requests - as happening on ESP8266
    // Turn off C++ exceptions. Worth 75,166 bytes on c3_pico (73.3% of the app partition down to
    // ~69.1%): ~53k of that is .eh_frame unwind tables and ~22k is the exception-handling code
    // itself. Nothing in Frugal-IoT catches anything except the LoRaMesher glue in
    // system/loramesher.cpp, so on a non-LoRa board this changes no behaviour.
    // LoRaMesher DOES throw, in ten-odd files, so the LoRa boards take this flag back off again
    // with build_unflags below - see common.build_unflags_loramesher. Removing it that way is
    // free; countering it with -fexceptions instead would cost those boards 6,232 bytes, because
    // -fexceptions also adds unwind tables to C sources that the default leaves out.
    // Note PlatformIO's "Flash: nn%" line does not count .eh_frame, so on the RISC-V boards the
    // real firmware.bin is bigger than reported (c3_pico was 73.3% real vs 70.0% reported). The
    // Xtensa boards fold .eh_frame into .flash.rodata, so their reported figure is about right.
    //-fno-exceptions
    // Uncomment debug lines before as needed
// #define ACTUATOR_LCD_DEBUG
// #define CONTROL_BLINKEN_DEBUG
// #define CONTROL_CLIMATE_DEBUG
// #define CONTROL_LOGGERFS_DEBUG
// #define SENSOR_BH1750_DEBUG
// #define SENSOR_DHT_DEBUG
// #define SENSOR_AHT_DEBUG
// #define SENSOR_ENS160_DEBUG
// #define SENSOR_LOADCELL_DEBUG
// #define SENSOR_MS5803_DEBUG
// #define SENSOR_SHT_DEBUG
// #define SENSOR_SOIL_DEBUG
// #define SYSTEM_DISCOVERY_DEBUG
// #define SYSTEM_FRUGAL_DEBUG
// #define SYSTEM_LITTLEFS_DEBUG
#define SYSTEM_LITTLEFS_SUPPORTDEPRECATED // one-shot migration of saved config from /<id>/<leaf>
                                         // directories to flat /<id>.<leaf> files. A LittleFS
                                         // directory costs a 2-block metadata pair (8KB), so the
                                         // old layout filled a 128KB partition after 15 modules.
                                         // Remove once no board in the field has the old layout.
// #define SYSTEM_FS_DEBUG_DIR // List the whole LittleFS directory tree at boot
// #define SYSTEM_MEMORY_DEBUG // cos seeing intermittent crash after some period (>7 mins)
// #define SYSTEM_MESSAGE_DEBUG // report messages received, sent, looped etc
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_OTA_DEBUG
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_WIFI_DEBUG

// Filled in by <name>-local.ini - the enrolment secret, and which server to build against.
// Empty here, so this file can be committed and a checkout without a local one still builds.
// build_flags_local =

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main = 
    // The enrolment secret, and which server this build is for - see <name>-local.ini
//     ${common.build_flags_local}

// project specific flags that are needed by the library 
// - being phased out (apart from debug flags) in favor of parameters from main.cpp
// but may be used where impact is across files, especially temporarily, for example where refactoring
// build_flags_library = 
#define SYSTEM_OTA_PREFIX "commonground"

// LoRaMesher throws, so the boards that use it need C++ exceptions back on. build_unflags REMOVES
// -fno-exceptions rather than countering it with -fexceptions - measured as byte-identical to a
// build that never had the flag, where -fexceptions would have cost 6,232 bytes.
// build_unflags_loramesher =
//     -fno-exceptions

// build flags that only relate to boards with LoRaMesher
// build_flags_loramesher = 
    // LoRaMesher, for now, has a lot of flags here, will move some of this to main.cpp
    // Both the t3_s3 and the ttgo boards we are testing use the same module
    // feel free to move into per-board [env] (and submit a PR) if your own setup differs
#define SYSTEM_LORAMESHER_FREQUENCY 915.0F // 868.0F for Europe, 915.0F for US/AU; 433.0F for Asia
#define SYSTEM_LORAMESHER_DEBUG // to get debugging at the app (not LoRaMesher or Radio) layers
// #define CORE_DEBUG_LEVEL 5 // To get lots of debugging out of LoraMesher
// #define RADIOLIB_DEBUG_BASIC // Debugging from RadioLib 

// Ask the linker for a map file. scripts/size_report.py reads it to say which archive members
// were linked in and which symbol pulled each one - the definitive answer to "is code from a
// sensor I am not using taking up flash". Build-time only, nothing reaches the device.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// Flags specific to project, but vary across dev-boards or variants
// build_flags = 
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_map}
   
// selecting a platform for board descriotions
// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; works in both PlatformIO and PIOArduino extensions
//platform_packages = framework-arduinoespressif32@3.3.2 ; also possible, but mostly unneeded and wont always work

// [env]
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// Unclear if next line causes problems either way - if commented out then doesnt recognize uploaded system 
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps =  ${common.lib_deps}
// lib_ldf_mode = chain
//Uncomment, if seeing exceptions need decoding
// build_type = debug
// monitor_filters = esp8266_exception_decoder
// monitor_filters = esp32_exception_decoder

// S2 Agri sensor including power control

// ===== [env:s2_mini] -> ARDUINO_LOLIN_S2_MINI
#if defined(ARDUINO_LOLIN_S2_MINI) || defined(S2_MINI)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI ; defines ARDUINO_LOLIN_S2_MINI variant=lolin_s2_mini
// board_build.partitions = min_spiffs.csv
// build_flags = 
    // Default SDA=33 SCL=35 avoid TX=39 RX=37 SPI 7,9,11,12 boot=0 and flashing=9-14,esp 11, 15-16 iff uses 32Mhz xtal; 39,40 iff use jtag debugging
    // Soil power ~6mA 
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini_2"
// #define SYSTEM_POWER_DEBUG
#define SENSOR_SOIL_POWER0_PIN 1
#define SENSOR_SOIL_POWER3v3_PIN 3
#define SENSOR_SOIL_PIN 4
#define SENSOR_SHT_POWER0_PIN 38
#define SENSOR_SHT_POWER3v3_PIN 21
    // SHT SDA 33, SCA 35 default I2C
#define SENSOR_DS18B20_POWER0_PIN 7
#define SENSOR_DS18B20_POWER3v3_PIN 8
#define SENSOR_DS18B20_PIN 11
    // GPIO5 is ADC1_CH4. This was pin 16, which is ADC2 - and ADC2 is shared with WiFi on
    // the S2, so a reading taken while the radio is busy can fail or come back stale.
    // NOTE this moves the wire: a board already built to read the divider on pin 16 has to
    // have that lead moved to pin 5.
#define SENSOR_BATTERY_PIN 5
#define SENSOR_BATTERY_VOLTAGE_DIVIDER 2 // Power 1 & 2 are both 100k+100k

#endif // ARDUINO_LOLIN_S2_MINI

// NODEMCU_TAMBAK, NODEMCU_LAUT are alternative [env:] settings for one board - at most one.
#if (defined(NODEMCU_TAMBAK) + defined(NODEMCU_LAUT)) > 1
  #error "Define at most one of NODEMCU_TAMBAK, NODEMCU_LAUT - they are alternative settings for the same board, and defining two applies both."
#endif
// ===== [env:nodemcu_tambak] -> ARDUINO_NodeMCU_32S, the DEFAULT for this board
#if (defined(ARDUINO_NodeMCU_32S) && !defined(NODEMCU_LAUT)) || defined(NODEMCU_TAMBAK)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = nodemcu-32s ; defines ARDUINO_NodeMCU_32S
// board_build.partitions = min_spiffs.csv
// lib_deps = 
//     ${common.lib_deps_lora}
// build_flags = 
//     ${common.build_flags}
//     ${common.build_flags_loramesher}
#define SYSTEM_OTA_SUFFIX "nodemcu_tambak"
#define ACTUATOR_RELAY_PIN 13
#define SENSOR_DHT_PIN 27 // Note not shown on schematic but in code.
// #define SENSOR_DHT_POWER3v3_PIN XX // Define and uncomment to power manage
#define SENSOR_DS18B20_PIN 4
// #define SENSOR_DS18B20_POWER3v3_PIN XX // Define and uncomment to power manage
#define SENSOR_PH_PIN 35
#define SENSOR_PH_SCALE -0.0051167
    // Flags whose value contains parentheses must be single-quoted or the shell that runs the
    // compiler treats them as syntax: "sh: syntax error near unexpected token `('"
#define SENSOR_PH_OFFSET (-15.5942/SENSOR_PH_SCALE) // raw reading at 0PH = PH at Raw=0 / Scale
// #define SENSOR_PH_POWER3v3_PIN XX // Define both (and pass to powerPins in main.cpp) to power manage
    // EC / salinity - a DFRobot analog EC meter (K=10), which reads mS/cm. Called TDS after
    // DFRobot's sample code, not because it is a ppm TDS meter. The wiki's
    // salinity = 0.0176 * raw - 6.9707 is exactly these two flags, since the library computes
    // (raw - offset) * scale and offset is given below as 6.9707/scale.
    // See https://wiki.colabs.commonroom.info/Sensor_Laut
#define SENSOR_TDS_PIN 32
#define SENSOR_TDS_SCALE 0.0176
#define SENSOR_TDS_OFFSET (6.9707/SENSOR_TDS_SCALE)
// #define SENSOR_TDS_POWER3v3_PIN XX // Define both (and pass to powerPins in main.cpp) to power manage
#define SENSOR_DO_PIN 25 // This what Solitude repo says, wiki/Sensor_Tam ak says 34
// #define SENSOR_DO_POWER3v3_PIN XX
// #define SYSTEM_LORAMESHER_WANT // nodemcu doesnt usually have LoRa
    // RS485 bus - the physical UART and transceiver, shared by every Modbus device
#define SYSTEM_RS485_TX_PIN 17
#define SYSTEM_RS485_RX_PIN 16
    // Transceiver direction pins - leave both undefined for a board that switches direction
    // automatically, or define DE only when DE and RE are tied together on the breakout.
    // These two are free on this board (relay is 13, DO is 34) so the wiki's pair works here.
// #define SYSTEM_RS485_DE_PIN 26
// #define SYSTEM_RS485_RE_PIN 25
// #define SYSTEM_MODBUS_DEBUG
    // Modbus slave id of the ultrasonic module - defining it is what enables Sensor_Ultrasonic
#define SENSOR_ULTRASONIC_SLAVE_ID 1
// #define SENSOR_ULTRASONIC_DEBUG
    // INA219 and BME280 on I2C
#define I2C_SDA 21 // nodemcu default is 18
#define I2C_SCL 22 // nodemcu default is 17
#define SENSOR_BME280_WANT // this board has a BME280 - add it in main.cpp
#define SENSOR_INA219_WANT // this board has an INA219 - add it in main.cpp
// #define SENSOR_INA219_ADDRESS 0x40 // default 0x40; 0x41..0x4F via the A0/A1 links
    // MUST match the shunt resistor fitted to the board. 0.1 is the common Adafruit/generic
    // breakout; high-current boards fit 0.002. Getting this wrong leaves shunt and bus correct
    // while current and power are silently wrong by the ratio of the two resistances.
#define SENSOR_INA219_SHUNT_OHMS 0.1
#define SENSOR_INA219_MAX_CURRENT 3.2 // A - at 0.1 ohm the hardware ceiling is 0.32V/0.1 = 3.2A
// #define SENSOR_INA219_CONFIG 0x3FFF // 32V, gain /8, 128-sample averaging, continuous
// #define SENSOR_INA219_DEBUG
// #define SENSOR_BME280_ADDRESS 0x77 // default is 0x76; 0x77 if SDO tied high
// #define SENSOR_BME280_DEBUG
#define LORA_IRQ 2 // from lpooking at schematic
#define LORA_RADIO_TYPE UNKNOWN
#define LORA_IO1 PIN_NONE // not connected
#define LORA_RST 14
#define LORA_CS 5
#define LORA_MOSI 23
#define LORA_MISO 19
#define LORA_SCK 18
// build_unflags = ${common.build_unflags_loramesher}

// Sensor Laut ("sea sensor") - water quality buoy, same sensor set as nodemcu_tambak but a
// different pinout. Pins, addresses and calibration from
// https://wiki.colabs.commonroom.info/Sensor_Laut
#endif // ARDUINO_NodeMCU_32S

// ----- [env:nodemcu_laut] also targets ARDUINO_NodeMCU_32S
// Only one env per board can be active in the Arduino IDE, and [env:nodemcu_tambak]
// is the default. To use this one instead, define NODEMCU_LAUT for the WHOLE
// build - it has to reach the library's sources too, so a #define in the .ino
// is not enough. Either:
//   put the flag -DNODEMCU_LAUT (not a #define) in a file called build_opt.h
//     beside the .ino - it survives this file being regenerated - or
//   #define NODEMCU_LAUT at the TOP of this file, which regenerating discards.
// To make it the default instead, and so need no define at all, set
//   custom_arduino_default = yes
// on [env:nodemcu_laut] in platformio.ini (and remove it from any other env for
// this board), then re-run scripts/generate_platform_h.py.
#if defined(NODEMCU_LAUT)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = nodemcu-32s ; defines ARDUINO_NodeMCU_32S
// board_build.partitions = min_spiffs.csv
// lib_deps = 
//     ${common.lib_deps_lora}
// build_flags = 
//     ${common.build_flags}
//     ${common.build_flags_loramesher}
#define SYSTEM_OTA_SUFFIX "nodemcu_laut"
#define ACTUATOR_RELAY_PIN 26 // 13 on nodemcu_tambak
#define SENSOR_DHT_PIN 27
#define SENSOR_DS18B20_PIN 4
#define SENSOR_PH_PIN 33 // 35 on nodemcu_tambak
#define SENSOR_PH_SCALE -0.0051167
    // Flags whose value contains parentheses must be single-quoted or the shell that runs the
    // compiler treats them as syntax: "sh: syntax error near unexpected token `('"
#define SENSOR_PH_OFFSET (-15.5942/SENSOR_PH_SCALE) // raw reading at 0PH = PH at Raw=0 / Scale
    // EC / salinity - a DFRobot analog EC meter (K=10), which reads mS/cm. Called TDS after
    // DFRobot's sample code, not because it is a ppm TDS meter. Same probe and the same
    // salinity = 0.0176 * raw - 6.9707 as nodemcu_tambak.
#define SENSOR_TDS_PIN 32
#define SENSOR_TDS_SCALE 0.0176
#define SENSOR_TDS_OFFSET (6.9707/SENSOR_TDS_SCALE)
#define SENSOR_DO_PIN 25
    // No RS485/Modbus on this board - the wiki lists no ultrasonic module.
    // I2C - the wiki does not state SDA/SCL, so these are the nodemcu_tambak pins. Check
    // against your board before trusting bme280 or ina219 readings.
#define I2C_SDA 21 // nodemcu default is 18
#define I2C_SCL 22 // nodemcu default is 17
#define SENSOR_BME280_WANT // this board has a BME280 - add it in main.cpp
// #define SENSOR_BME280_ADDRESS 0x76 // wiki says 0x76, which is the default
#define SENSOR_INA219_WANT // this board has an INA219 - add it in main.cpp
#define SENSOR_INA219_ADDRESS 0x41 // NOT the 0x40 default - wiki says 0x41 (A0 linked)
    // MUST match the shunt resistor fitted to the board. The wiki does not say which one it
    // is, so this is the common 0.1 ohm breakout value - if the board is a high-current one
    // with 0.002 ohm, shunt and bus stay correct while current and power read 50x low.
#define SENSOR_INA219_SHUNT_OHMS 0.1
#define SENSOR_INA219_MAX_CURRENT 3.2 // A - at 0.1 ohm the hardware ceiling is 0.32V/0.1 = 3.2A
    // LoRa - the wiki gives ss/rst/dio0 only, so the SPI pins below are the VSPI defaults
    // (as on nodemcu_tambak). Uncomment SYSTEM_LORAMESHER_WANT to actually run the mesh;
    // the 915MHz in build_flags_loramesher already matches what the wiki specifies.
// #define SYSTEM_LORAMESHER_WANT
#define LORA_RADIO_TYPE UNKNOWN
#define LORA_CS 5
#define LORA_RST 12 // 14 on nodemcu_tambak
#define LORA_IRQ 2
#define LORA_IO1 PIN_NONE // not connected
#define LORA_MOSI 23
#define LORA_MISO 19
#define LORA_SCK 18
// build_unflags = ${common.build_unflags_loramesher}

// To add another board, copy example from another examples/*/platform.ini and edit in pins etc.

// ===== LORA BOARDS - ALL ESP32 ======================================

#endif // NODEMCU_LAUT

// ===== [env:heltec_wifi_lora_32_V32] -> ARDUINO_heltec_wifi_lora_32_V3
#if defined(ARDUINO_heltec_wifi_lora_32_V3) || defined(HELTEC_WIFI_LORA_32_V32)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = heltec_wifi_lora_32_V3  ; defines ARDUINO_heltec_wifi_lora_32_V3; default variant heltec_wifi_lora_32_V3
// build_flags = 
//     ${common.build_flags}
#define ARDUINO_heltec_wifi_lora_32_V32 // If using 3.2 board uncomment this
#define SYSTEM_OTA_SUFFIX "heltec_wifi_lora_32_v32"
//     ${common.build_flags_loramesher}
// build_unflags = ${common.build_unflags_loramesher}
// board_build.partitions = min_spiffs.csv ; heltec_wifi_lora_32_v3 default of default_8MB.csv is fine (3.3Mb apps)
// lib_deps = 
//     ${common.lib_deps_lora_oled}
#endif // ARDUINO_heltec_wifi_lora_32_V3

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: LOLIN S2 Mini / NodeMCU-32S / Heltec WiFi LoRa 32(V3)"
#endif

#endif // PLATFORM_H
