#!/usr/bin/env python3
"""
Price each optional module in flash bytes.

Builds a minimal sketch, then rebuilds it once per module with just that one module added, and
reports the difference in image size. The point is to find modules that drag in far more than
they look like they should - the way LoRaMesher's std::ostringstream turned out to be worth
230,464 bytes of C++ locale machinery. That was invisible until measured, so this measures
everything rather than guessing which to suspect.

It never touches src/main.cpp. Generated sketches go in a scratch directory and PLATFORMIO_SRC_DIR
points the build at them; PLATFORMIO_BUILD_DIR keeps the object files out of your real .pio/build
so your normal builds are not disturbed or invalidated. The scratch build dir is reused between
modules on purpose - only main.cpp and the newly-reached library objects recompile, so after the
first build each module costs seconds rather than minutes.

Usage:
    lib/Frugal-IoT/scripts/price_modules.py                        # every module, on c3_pico
    lib/Frugal-IoT/scripts/price_modules.py -e ttgo-lora32-v21
    lib/Frugal-IoT/scripts/price_modules.py --only ds18b20 loadcell
    lib/Frugal-IoT/scripts/price_modules.py --list
    lib/Frugal-IoT/scripts/price_modules.py --markdown             # table ready to paste into the results file
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from size_report import elf_alloc, find_project                      # noqa: E402

PROJECT = find_project()
SCRATCH = Path(os.environ.get(
    "FRUGAL_PRICE_SCRATCH",
    "/private/tmp/frugal-iot-price-modules"))

# The skeleton every generated sketch shares. Deliberately minimal: no optional sensor, so the
# baseline is "the framework, WiFi, MQTT, the web portal and nothing else".
SKELETON = """\
// GENERATED by scripts/price_modules.py - do not edit, do not commit.
// Minimal sketch used to measure what one module costs in flash.
#include "Frugal-IoT.h"

System_Frugal frugal_iot(SYSTEM_FRUGAL_ORG, SYSTEM_FRUGAL_PROJECT, "price", "Module pricing");

%(globals)s

void setup() {
  frugal_iot.pre_setup();
  frugal_iot.configure_mqtt("frugaliot.naturalinnovation.org", "dev", "public");
  frugal_iot.configure_power(Power_Loop, 30000, 30000);
%(body)s
  frugal_iot.setup();
}

void loop() {
  frugal_iot.loop();
}
"""

# name -> (setup-body lines, extra build flags, file-scope lines)
# Signatures taken from the headers in lib/Frugal-IoT/src; a module whose constructor changes will
# fail to compile and be reported as such rather than silently skipped.
MODULES = {
    # --- sensors that bring a third-party library with them ------------------------------------
    "ds18b20": (
        '  frugal_iot.sensors->add(new Sensor_DS18B20("ds18b20", "Soil Temp", 6, 0, true));',
        [], ""),                                    # DallasTemperature + OneWire
    "loadcell": (
        '  frugal_iot.sensors->add(new Sensor_LoadCell("loadcell", "Weight", 5000.0f, "blue",'
        ' true, 6, 7, 10, 0, 1));',
        [], ""),                                    # HX711
    "bh1750": (
        '  frugal_iot.sensors->add(new Sensor_BH1750("bh1750", "Light", 0x23, &I2C_WIRE, true));',
        [], ""),                                    # BH1750
    "dht": (
        '  frugal_iot.sensors->add(new Sensor_DHT("DHT", 6, true));',
        [], ""),                                    # DHTNEW
    "sht": (
        '  frugal_iot.sensors->add(new Sensor_SHT("SHT", 0x44, &I2C_WIRE, true));',
        [], ""),                                    # SHT85
    "gps": (
        '  frugal_iot.sensors->add(new Sensor_GPS("GPS", &Serial1, 20, 21));',
        [], '#include "sensor/gps.h"'),              # TinyGPSPlus; gps.h not in Frugal-IoT.h
    "ultrasonic": (
        '  frugal_iot.sensors->add(new Sensor_Ultrasonic("ultrasonic", "Depth", 7500.0f, "blue",'
        ' true, rs485));',
        # SENSOR_ULTRASONIC_SLAVE_ID switches on SYSTEM_MODBUS_WANT, which then #errors unless
        # the RS485 UART pins are given as well.
        ["-D SENSOR_ULTRASONIC_SLAVE_ID=1", "-D SYSTEM_RS485_RX_PIN=20",
         "-D SYSTEM_RS485_TX_PIN=21"],
        "System_RS485* rs485 = nullptr;"),          # ModbusMaster
    "lcd": (
        '  frugal_iot.actuators->add(new Actuator_LCD());',
        ["-D ACTUATOR_LCD_WANT"], ""),              # hd44780

    # --- sensors with no external library, to catch anything pulling in std:: machinery --------
    "aht21": (
        '  frugal_iot.sensors->add(new Sensor_AHT21("AHT21"));', [], ""),
    "ens160": (
        '  frugal_iot.sensors->add(new Sensor_ENS160("ENS160"));', [], ""),
    "bmp280": (
        '  frugal_iot.sensors->add(new Sensor_BMP280("BMP280"));', [], ""),
    "bme280": (
        '  frugal_iot.sensors->add(new Sensor_BME280("BME280"));', [], ""),
    "bme680": (
        '  frugal_iot.sensors->add(new Sensor_BME680("BME680"));', [], ""),
    "ina219": (
        '  frugal_iot.sensors->add(new Sensor_INA219("ina219", "Current"));', [], ""),
    "ms5803": (
        '  frugal_iot.sensors->add(new Sensor_ms5803("ms5803", "Pressure", 0x76));', [], ""),
    "soil": (
        '  frugal_iot.sensors->add(new Sensor_Soil("soil", "Soil", 4, 0, 1.0f, "brown", true));',
        [], ""),
    "dissolvedoxygen": (
        '  frugal_iot.sensors->add(new Sensor_DissolvedOxygen("do", "DO", 4));', [], ""),
    "battery": (
        '  frugal_iot.sensors->add(new Sensor_Battery(0, 2));', [], ""),

    # --- controls -----------------------------------------------------------------------------
    "blinken": (
        '  frugal_iot.controls->add(new Control_Blinken("blinken", "Blink", 1.0f, 1.0f));',
        [], ""),
    "hysteresis": (
        '  frugal_iot.controls->add(new Control_Hysteresis("hyst", "Control", 50, 1, 0, 100));',
        [], ""),
    # Frugal-IoT.h does not include control/carousel.h (nor control/oled.h or control/logger.h),
    # so a sketch has to include it directly - which is why this needs the third field.
    "carousel": (
        '  frugal_iot.controls->add(new Control_Carousel("carousel"));', [],
        '#include "control/carousel.h"'),
    "gsheets": (
        '  frugal_iot.controls->add(new Control_Gsheets("gsheets",'
        ' "https://example.invalid/exec"));',
        [], ""),
    "logger_fs": (
        '  frugal_iot.controls->add(new Control_LoggerFS("loggerfs", frugal_iot.fs_LittleFS,'
        ' "/log", 0, std::vector<IN*>{}));',
        [], ""),
}


def image_bytes(elf: Path) -> int:
    """Flash+RAM bytes the image actually occupies, from the ELF's own section headers.

    Deliberately measured from the ELF rather than from firmware.bin. Only the deltas matter here,
    and firmware.bin is this total plus a constant ~153-byte header - but producing the .bin needs
    esptool, the bootloader and the partition table, which is both slower and a recurring source
    of unrelated breakage. Building only the ELF
    sidesteps all of it.
    """
    return sum(size for size, nb in elf_alloc(elf).values() if not nb)


def build(env, src_dir: Path, build_dir: Path, extra_flags):
    """Run pio for one generated sketch. Returns (image bytes, error text or None)."""
    envv = dict(os.environ)
    envv["PLATFORMIO_SRC_DIR"] = str(src_dir)
    envv["PLATFORMIO_BUILD_DIR"] = str(build_dir)
    if extra_flags:
        # PlatformIO appends this to the env's build_flags rather than replacing them.
        envv["PLATFORMIO_BUILD_FLAGS"] = " ".join(extra_flags)
    elf = build_dir / env / "firmware.elf"
    if elf.exists():
        elf.unlink()                       # never report a stale ELF as this module's result
    r = subprocess.run(["pio", "run", "-e", env, "-t", str(elf)], cwd=PROJECT, env=envv,
                       capture_output=True, text=True)
    # Judge success on the ELF existing, not on the exit code. Asking for the ELF target still
    # drags bootloader.bin along, and that step needs esptool - which breaks periodically on this
    # machine for reasons that have nothing to do with the sketch (see the esptool notes). The ELF
    # is linked before that fails, so if it is there the measurement is good.
    if not elf.exists():
        errs = [l for l in (r.stdout + r.stderr).splitlines()
                if re.search(r"\berror\b", l, re.I)]
        return None, "\n".join(errs[:4]) or "build failed with no recognisable error line"
    return image_bytes(elf), None


def write_sketch(dirpath: Path, body="", globals_="") -> Path:
    dirpath.mkdir(parents=True, exist_ok=True)
    (dirpath / "main.cpp").write_text(SKELETON % {"body": body, "globals": globals_})
    return dirpath


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-e", "--env", default="c3_pico")
    ap.add_argument("--only", nargs="*", help="just these modules")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--keep", action="store_true", help="leave the scratch tree for inspection")
    args = ap.parse_args()

    if args.list:
        for k in sorted(MODULES):
            print(k)
        return

    wanted = args.only or sorted(MODULES)
    unknown = [m for m in wanted if m not in MODULES]
    if unknown:
        sys.exit(f"unknown module(s): {', '.join(unknown)}\nsee --list")

    build_dir = SCRATCH / "build"
    src_root = SCRATCH / "src"
    print(f"env: {args.env}   scratch: {SCRATCH}")
    print("(first build is slow; the rest reuse the object tree)\n")

    print(f"{'baseline':<20}", end="", flush=True)
    base, err = build(args.env, write_sketch(src_root / "_baseline"), build_dir, [])
    if base is None:
        sys.exit(f"\nbaseline build failed:\n{err}")
    print(f"{base:>12,} bytes")

    results = []
    for name in wanted:
        body, flags, globs = MODULES[name]
        print(f"{name:<20}", end="", flush=True)
        size, err = build(args.env, write_sketch(src_root / name, body, globs), build_dir, flags)
        if size is None:
            print("  FAILED")
            results.append((None, name, err))
        else:
            print(f"{size:>12,}   {size - base:>+9,}")
            results.append((size - base, name, None))

    ok = sorted((r for r in results if r[0] is not None), reverse=True)
    bad = [r for r in results if r[0] is None]

    print(f"\n{'=' * 62}\nCost of each module on {args.env}, over a {base:,} byte baseline\n"
          f"{'=' * 62}")
    if args.markdown:
        print(f"\n| module | image bytes | cost |\n|---|---|---|")
        print(f"| *(baseline)* | {base:,} | — |")
        for delta, name, _ in ok:
            print(f"| `{name}` | {base + delta:,} | {delta:+,} |")
    else:
        for delta, name, _ in ok:
            print(f"  {name:<20}{delta:>+10,}")
    for _d, name, err in bad:
        print(f"  {name:<20}   did not build: {err.splitlines()[0][:80] if err else '?'}")

    if not args.keep:
        shutil.rmtree(SCRATCH, ignore_errors=True)
    else:
        print(f"\nscratch kept at {SCRATCH}")


if __name__ == "__main__":
    main()
